// ============================================================
// Generated by Web Recorder - 2026-09-23 14:23
// ============================================================

import { Page } from '@playwright/test';
import { BasePage } from '../framework/base/BasePage';

export class LoginPage extends BasePage {
  static readonly LOGIN_WITH_MICROSOFT_BUTTON = 'text=Login with Microsoft';
  static readonly LOGINFMT = '[name=\'loginfmt\']';
  static readonly IDSIBUTTON9 = '#idSIButton9';
  static readonly PASSWD = '[name=\'passwd\']';

  constructor(page: Page) {
    super(page);
  }

  /**
   * Performs end-to-end Microsoft SSO login popup flow.
   */
  async loginWithMicrosoft(
    url = 'https://assetmanagementqa.rishabhsoft.com/',
    loginfmt?: string,
    passwd?: string
  ): Promise<void> {
    await this.goto(url);

    // Wait for popup window triggered by click
    const [popup] = await Promise.all([
      this.page.waitForEvent('popup'),
      this.click('LOGIN_WITH_MICROSOFT_BUTTON', LoginPage.LOGIN_WITH_MICROSOFT_BUTTON),
    ]);
    await popup.waitForLoadState('domcontentloaded');
    const popupPage = new LoginPage(popup);

    if (loginfmt) {
      await popupPage.fill('LOGINFMT', LoginPage.LOGINFMT, loginfmt);
      await popupPage.click('IDSIBUTTON9', LoginPage.IDSIBUTTON9);
    }
    if (passwd) {
      await popupPage.fill('PASSWD', LoginPage.PASSWD, passwd);
      await popupPage.click('IDSIBUTTON9', LoginPage.IDSIBUTTON9);
      // Microsoft SSO may show 'Stay signed in?' prompt with idSIButton9
      try {
        await popupPage.click('IDSIBUTTON9', LoginPage.IDSIBUTTON9);
      } catch {}
    }

    // Wait for popup to complete and return to main page
    if (!popup.isClosed()) {
      try {
        await popup.waitForEvent('close', { timeout: 15000 });
      } catch {}
    }
    await this.page.waitForLoadState('domcontentloaded');
  }
}

