// ============================================================
// Generated by Web Recorder - 2026-09-23 14:30
// ============================================================

import { Page } from '@playwright/test';
import { BasePage } from '../framework/base/BasePage';

export class ManagmentPage extends BasePage {
  static readonly USER_MANAGEMENT_BUTTON = 'text=User Management';
  static readonly ASSIGN_ROLE_BUTTON = 'text=+ Assign Role';
  static readonly DIV_CSS_19BB58M = 'div.css-19bb58m';
  static readonly REACT_SELECT_2_INPUT = '#react-select-2-input';
  static readonly RACHIT_MEHTA_BUTTON = 'text=Rachit Mehta';
  static readonly ADMIN_TEAM_FINANCE_TEAM_BUTTON = 'text=Admin Team Finance Team';
  static readonly CANCEL_BUTTON = 'text=Cancel';
  static readonly CONTINUE_BUTTON = 'text=Continue';

  constructor(page: Page) {
    super(page);
  }
}
