package recorder;

// ============================================================
// Generated by Web Recorder — 2026-09-05 12:08
// Start URL: https://riloma-web-portal.x97g.com/login
// Browser:   chrome
// Data File: src/test/resources/data/RilomaLoginData.json
// ============================================================

import com.microsoft.playwright.*;
import org.testng.annotations.*;
import pageobjects.RilomaLogin;
import utils.SelfHealingLocator;

public class GeneratedWebTest {

    private Playwright playwright;
    private Browser browser;
    private BrowserContext context;
    private Page page;

    @BeforeClass
    public void setUp() {
        playwright = Playwright.create();
        browser = playwright.chromium().launch(
            new BrowserType.LaunchOptions().setHeadless(false).setArgs(java.util.Arrays.asList("--start-maximized"))
        );
        context = browser.newContext(
            new Browser.NewContextOptions().setViewportSize(null)
        );
        page = context.newPage();
    }

    @DataProvider(name = "testData")
    public Object[][] getTestData() {
        return utils.JsonDataReader.loadData("src/test/resources/data/RilomaLoginData.json");
    }

    @Test(dataProvider = "testData")
    public void testRecordedFlow(String identifier, String password) {
        page.navigate("https://riloma-web-portal.x97g.com/login");
        SelfHealingLocator.fill(page, "IDENTIFIER", RilomaLogin.IDENTIFIER, identifier);
        SelfHealingLocator.fill(page, "PASSWORD", RilomaLogin.PASSWORD, password);
        SelfHealingLocator.click(page, "LOGIN_BUTTON", RilomaLogin.LOGIN_BUTTON);
    }

    @AfterClass
    public void tearDown() {
        if (page    != null) page.close();
        if (context != null) context.close();
        if (browser != null) browser.close();
        if (playwright != null) playwright.close();
    }
}
