package recorder;

// ============================================================
// Generated by Web Recorder - 2026-09-23 14:23
// Start URL: https://assetmanagementqa.rishabhsoft.com/
// Browser:   chrome
// Data File: src/test/resources/data/LoginData.json
// ============================================================

import com.microsoft.playwright.*;
import org.testng.annotations.*;
import pageobjects.Login;
import utils.SelfHealingLocator;

public class LoginTest {

    private Playwright playwright;
    private Browser browser;
    private BrowserContext context;
    private Page page;

    @BeforeClass
    public void setUp() {
        java.util.Map<String, String> env = new java.util.HashMap<>(System.getenv());
        env.put("NODE_TLS_REJECT_UNAUTHORIZED", "0");
        playwright = Playwright.create(new Playwright.CreateOptions().setEnv(env));
        browser = playwright.chromium().launch(
            new BrowserType.LaunchOptions().setHeadless(false).setArgs(java.util.Arrays.asList("--start-maximized"))
        );
        context = browser.newContext(
            new Browser.NewContextOptions().setViewportSize(null)
        );
        page = context.newPage();
    }

    @DataProvider(name = "testData")
    public Object[][] getTestData() {
        return utils.JsonDataReader.loadData("src/test/resources/data/LoginData.json");
    }

    @Test(dataProvider = "testData")
    public void testRecordedFlow(String loginfmt, String passwd) {
        page.navigate("https://assetmanagementqa.rishabhsoft.com/");
        // Wait for popup window triggered by click
        Page popup = page.waitForPopup(() -> {
            SelfHealingLocator.click(page, "LOGIN_WITH_MICROSOFT_BUTTON", Login.LOGIN_WITH_MICROSOFT_BUTTON);
        });
        popup.waitForLoadState();

        SelfHealingLocator.fill(popup, "LOGINFMT", Login.LOGINFMT, loginfmt);
        SelfHealingLocator.click(popup, "IDSIBUTTON9", Login.IDSIBUTTON9);
        SelfHealingLocator.fill(popup, "PASSWD", Login.PASSWD, passwd);
        SelfHealingLocator.click(popup, "IDSIBUTTON9", Login.IDSIBUTTON9);

        // Wait for popup to complete and return to main page
        try {
            popup.waitForClose(new Page.WaitForCloseOptions().setTimeout(15000), () -> {});
        } catch (Exception ignored) {}

    }

    @AfterClass
    public void tearDown() {
        if (page    != null) page.close();
        if (context != null) context.close();
        if (browser != null) browser.close();
        if (playwright != null) playwright.close();
    }
}
