package recorder;

// ============================================================
// Generated by Web Recorder - 2026-09-23 14:30
// Start URL: https://assetmanagementqa.rishabhsoft.com/
// Browser:   chrome
// Data File: src/test/resources/data/ManagmentData.json
// ============================================================

import com.microsoft.playwright.*;
import org.testng.annotations.*;
import pageobjects.Managment;
import utils.SelfHealingLocator;

public class ManagmentTest {

    private Playwright playwright;
    private Browser browser;
    private BrowserContext context;
    private Page page;

    @BeforeClass
    public void setUp() {
        java.util.Map<String, String> env = new java.util.HashMap<>(System.getenv());
        env.put("NODE_TLS_REJECT_UNAUTHORIZED", "0");
        playwright = Playwright.create(new Playwright.CreateOptions().setEnv(env));
        browser = playwright.chromium().launch(
            new BrowserType.LaunchOptions().setHeadless(false).setArgs(java.util.Arrays.asList("--start-maximized"))
        );
        context = browser.newContext(
            new Browser.NewContextOptions().setViewportSize(null)
        );
        page = context.newPage();
    }

    @DataProvider(name = "testData")
    public Object[][] getTestData() {
        return utils.JsonDataReader.loadData("src/test/resources/data/ManagmentData.json");
    }

    @Test(dataProvider = "testData")
    public void testRecordedFlow(String reactSelect2Input, String adminTeamFinanceTeamButton) {
        page.navigate("https://assetmanagementqa.rishabhsoft.com/dashboard/branchadmin");
        SelfHealingLocator.click(page, "USER_MANAGEMENT_BUTTON", Managment.USER_MANAGEMENT_BUTTON);
        SelfHealingLocator.click(page, "ASSIGN_ROLE_BUTTON", Managment.ASSIGN_ROLE_BUTTON);
        SelfHealingLocator.click(page, "DIV_CSS_19BB58M", Managment.DIV_CSS_19BB58M);
        SelfHealingLocator.fill(page, "REACT_SELECT_2_INPUT", Managment.REACT_SELECT_2_INPUT, reactSelect2Input);
        SelfHealingLocator.click(page, "RACHIT_MEHTA_BUTTON", Managment.RACHIT_MEHTA_BUTTON);
        SelfHealingLocator.click(page, "REC_RECORDING_ACTIVE_DASHBOARD_USER_MANAGEMENT_LOCATION_MANAGEMENT_VENDOR_M_BUTTON", Managment.REC_RECORDING_ACTIVE_DASHBOARD_USER_MANAGEMENT_LOCATION_MANAGEMENT_VENDOR_M_BUTTON);
        SelfHealingLocator.selectOption(page, "ADMIN_TEAM_FINANCE_TEAM_BUTTON", Managment.ADMIN_TEAM_FINANCE_TEAM_BUTTON, adminTeamFinanceTeamButton);
        SelfHealingLocator.click(page, "CANCEL_BUTTON", Managment.CANCEL_BUTTON);
        SelfHealingLocator.click(page, "CONTINUE_BUTTON", Managment.CONTINUE_BUTTON);
    }

    @AfterClass
    public void tearDown() {
        if (page    != null) page.close();
        if (context != null) context.close();
        if (browser != null) browser.close();
        if (playwright != null) playwright.close();
    }
}
