// ============================================================
// Generated by Web Recorder - 2026-09-23 14:23
// Start URL: https://assetmanagementqa.rishabhsoft.com/
// Browser:   chrome
// Framework: Playwright TypeScript POM + TestNG
// ============================================================

import { test, expect } from '../framework/base/BaseTest';
import { LoginPage } from '../pages/LoginPage';
import { DataProvider } from '../framework/utils/DataProvider';

const testData = DataProvider.loadJson<any>('LoginData.json');

for (const { loginfmt, passwd } of testData) {
  test(`testRecordedFlow - ${loginfmt}`, async ({ page }) => {
    const loginpage = new LoginPage(page);
    await loginpage.loginWithMicrosoft('https://assetmanagementqa.rishabhsoft.com/', loginfmt, passwd);
  });
}
