// ============================================================
// Generated by Web Recorder - 2026-09-23 14:30
// Start URL: https://assetmanagementqa.rishabhsoft.com/
// Browser:   chrome
// Framework: Playwright TypeScript POM + TestNG
// ============================================================

import { test, expect } from '../framework/base/BaseTest';
import { ManagmentPage } from '../pages/ManagmentPage';
import { LoginPage } from '../pages/LoginPage';
import { DataProvider } from '../framework/utils/DataProvider';

const testData = DataProvider.loadJson<any>('ManagmentData.json');

// Auto-injected by Test Integrator: Execute login before running management actions
test.beforeEach(async ({ page }) => {
  const loginPage = new LoginPage(page);
  const [credentials] = DataProvider.loadJson<any>('LoginData.json');
  await loginPage.loginWithMicrosoft(
    'https://assetmanagementqa.rishabhsoft.com/',
    credentials?.loginfmt,
    credentials?.passwd
  );
});

for (const { reactSelect2Input, adminTeamFinanceTeamButton } of testData) {
  test(`testRecordedFlow - ${reactSelect2Input}`, async ({ page }) => {
    const managmentpage = new ManagmentPage(page);

    await managmentpage.click("USER_MANAGEMENT_BUTTON", ManagmentPage.USER_MANAGEMENT_BUTTON);
    await managmentpage.click("ASSIGN_ROLE_BUTTON", ManagmentPage.ASSIGN_ROLE_BUTTON);
    await managmentpage.click("DIV_CSS_19BB58M", ManagmentPage.DIV_CSS_19BB58M);
    await managmentpage.fill("REACT_SELECT_2_INPUT", ManagmentPage.REACT_SELECT_2_INPUT, reactSelect2Input);
    await managmentpage.click("RACHIT_MEHTA_BUTTON", ManagmentPage.RACHIT_MEHTA_BUTTON);
    await managmentpage.selectOption("ADMIN_TEAM_FINANCE_TEAM_BUTTON", ManagmentPage.ADMIN_TEAM_FINANCE_TEAM_BUTTON, adminTeamFinanceTeamButton);
    await managmentpage.click("CANCEL_BUTTON", ManagmentPage.CANCEL_BUTTON);
    await managmentpage.click("CONTINUE_BUTTON", ManagmentPage.CONTINUE_BUTTON);
  });
}
